symbols: 
  - BTC/USD
  - LINK/BTC
  - UNI/US
  - BCH/USD
  - AAPL
  - DELL
data_preference: yf # 'yf' - yfinance, 'alpaca' - tahaj z alpacy, 'longer_period' - tahaj odkial je dlhsia perioda
rolling_split_params: 
  n_periods: 15
  period_ratio: 0.35
  period_years_max: 3
strategies: 
  - hhhl  
strategy_params:
  hhhl:
    fees: 0.001
    slippage: 0.0001
    stop_loss: 0.1
    param_ranges:
      window_entry: [1, 9]
      hh_hl_counts: [1, 5]
      window_exit: [1, 9]
      lh_counts: [1, 5]
eval_params:
  filters:
    sharpe_ratio_min: 0
    total_returns_min: 0
    trades_in_year_min: 6
  clustering:
    explore: false
    max_clusters: 40
    dataset_size_for_max_clusters: 700
    scaling_factor: 20 # 1 cluster pre kazdych 20 parameter kombinacii
    min_items_to_cluster: 100
    cluster_cols:
      - Total Return [%]_mean
      - Sharpe Ratio_mean
      - Max Drawdown [%]_mean
      - Total Trades_mean
      - Total Return [%]_std_perc
      - Sharpe Ratio_std_perc
      - Sharpe Ratio_min
      - Total Return [%]_min
      - Total Trades_min
    filters:
      trades_in_year_mean: 20 # minimalny priemer poctu obchodov za rok
      sharpe_ratio_mean: 0.6 # problem bude pri roznych periodach, lebo vacsie SR koreluje s dlhsou periodou (daj ako % z max SR)   
      items_from_cluster_nr: 5 # kolko vyberem z kazdeho clustra
  final_params:
    final_params_nr: 5
    force: false # ak true, tak v pripade ked "filters" bude mat menej ako 5 - uvolni filter aby ich bolo aspon 5. Ak 5 - min_items_to_cluster, tak uvolni filtre.
    # ked teda dosiahnem 100, tak oklastruj, ale ked filter po klusteringu bude mat < 5, tak uvolni cluster filtre aby ich bolo aspon 5, potom sortni podla stdev a zober top 5