p1:
  symbols:
    AAPL:
      hhhl:
        window_entry: 3
        hh_hl_counts: 1
        window_exit: 4
        lh_counts: 4
    BTC/USD:
      hhhl:
        window_entry: 3
        hh_hl_counts: 1
        window_exit: 7
        lh_counts: 4
    LINK/BTC:
      hhhl:
        window_entry: 8
        hh_hl_counts: 2
        window_exit: 2
        lh_counts: 2
    DELL:
      hhhl:
        window_entry: 2
        hh_hl_counts: 1
        window_exit: 4
        lh_counts: 4
  weights: 
    initial: equal
    running: equal
  initial_portfolio_size: 1000
  data_preference: alpaca
p2:
  symbols:
    NVDA:
      hhhl:
        window_entry: 3
        hh_hl_counts: 1
        window_exit: 5
        lh_counts: 4
    MSFT:
      hhhl:
        window_entry: 2
        hh_hl_counts: 1
        window_exit: 8
        lh_counts: 5
    AMZN:
      hhhl:
        window_entry: 8
        hh_hl_counts: 2
        window_exit: 2
        lh_counts: 2
  weights: 
    initial: equal
    running: win_rate
    running_params:
        min_trades: 5
        min_weight: 0.05
        min_symbols: 2 # kolko symbolov je mat min na kalkulaciu running weight. Ak nejaky symbol nebude mat dostatocny min trades, bude mat min vahu   
  initial_portfolio_size: 1000
  data_preference: yf

#TODO sprav p3 kde budu manualne vahy
