p1:
  symbols:
    PBR:
      hhhl_ml1:
        params:
          probability_threshold: 0.5
        stoploss: 0.1
        take_profit: None #TODO add param probability_threshold
        
    T:
      hhhl_ml1:
        params:
          probability_threshold: 0.5
        stoploss: 0.1
        take_profit: None
    VALE:
      hhhl_ml1:
        params:
          probability_threshold: 0.5
        stoploss: 0.1
        take_profit: None
    FTNT:
      hhhl_ml1:
        params:
          probability_threshold: 0.5
        stoploss: 0.1
        take_profit: None
    BX:
      hhhl_ml1:
        params:
          probability_threshold: 0.5
        stoploss: 0.1
        take_profit: None
    MO:
      hhhl_ml1:
        params:
          probability_threshold: 0.5
        stoploss: 0.1
        take_profit: None
    NVDA:
      hhhl_ml1:
        params:
          probability_threshold: 0.5
        stoploss: 0.1
        take_profit: None
    TNA:
      hhhl_ml1:
        params:
          probability_threshold: 0.5
        stoploss: 0.1
        take_profit: None
    BSX:
      hhhl_ml1:
        params:
          probability_threshold: 0.5
        stoploss: 0.1
        take_profit: None
    PANW:
      hhhl_ml1:
        params:
          probability_threshold: 0.5
        stoploss: 0.1
        take_profit: None
    VZ:
      hhhl_ml1:
        params:
          probability_threshold: 0.5
        stoploss: 0.1
        take_profit: None
    ANET:
      hhhl_ml1:
        params:
          probability_threshold: 0.5
        stoploss: 0.1
        take_profit: None
    WBD:
      hhhl_ml1:
        params:
          probability_threshold: 0.5
        stoploss: 0.1
        take_profit: None
  weights: 
    initial: equal
    running: equal
  portfolio_size: 1300
  data_preference: yf
  min_available_cash: 100
  model_folder: 
    hhhl_ml1: '../models/1st_test'
  ml_strategies_setup:
    hhhl_ml1:
      param_ranges:
        window_entry: [2, 9]
        hh_hl_counts: [1, 5]
        window_exit: [2, 9]
        lh_counts: [1, 5]
p2:
  symbols:
    UPRO:
      hhhl_ml1:
        params:
          probability_threshold: 0.5
        stoploss: 0.1
        take_profit: None
    IYR:
      hhhl_ml1:
        params:
          probability_threshold: 0.5
        stoploss: 0.1
        take_profit: None
    AMZN:
      hhhl_ml1:
        params:
          probability_threshold: 0.5
        stoploss: 0.1
        take_profit: None
    MRK:
      hhhl_ml1:
        params:
          probability_threshold: 0.5
        stoploss: 0.1
        take_profit: None
    SHOP:
      hhhl_ml1:
        params:
          probability_threshold: 0.5
        stoploss: 0.1
        take_profit: None
    KEY:
      hhhl_ml1:
        params:
          probability_threshold: 0.5
        stoploss: 0.1
        take_profit: None
    IBM:
      hhhl_ml1:
        params:
          probability_threshold: 0.5
        stoploss: 0.1
        take_profit: None
    TSM:
      hhhl_ml1:
        params:
          probability_threshold: 0.5
        stoploss: 0.1
        take_profit: None
    CAG:
      hhhl_ml1:
        params:
          probability_threshold: 0.5
        stoploss: 0.1
        take_profit: None
    MMM:
      hhhl_ml1:
        params:
          probability_threshold: 0.5
        stoploss: 0.1
        take_profit: None
    MDLZ:
      hhhl_ml1:
        params:
          probability_threshold: 0.5
        stoploss: 0.1
        take_profit: None
    HBAN:
      hhhl_ml1:
        params:
          probability_threshold: 0.5
        stoploss: 0.1
        take_profit: None
  weights: 
    initial: equal
    running: equal
  portfolio_size: 1200
  data_preference: yf
  min_available_cash: 100
  model_folder: 
    hhhl_ml1: '../models/1st_test' # produkcny folder na modely
  ml_strategies_setup:
    hhhl_ml1:
      param_ranges:
        window_entry: [2, 9]
        hh_hl_counts: [1, 5]
        window_exit: [2, 9]
        lh_counts: [1, 5]

